### ISSUE TITLE
查看原图不能获取正确的图片URL

### ISSUE THREAD

**Issue by houwj** [tiansh/yaofang#1]
Firefox 66.0.4
Violentmonkey  2.10.4

**Comment by tiansh** [comment]
1. 是每一条微博都这样还是某一条这样，给一个微博的链接（点微博的发布时间可以得到单条微博的链接）？
2. 无法获取正确 URL 表现的结果是什么样子，是展示了其他图片，还是没有展示图片？
3. 查看原图功能是怎么设置的（是否设置了点击图片直接打开，是否设置了右键打开），以及怎么使用的（点的图片还是右键菜单）？
4. 是脚本版的问题还是扩展版的问题？扩展不依赖于 Violent Monkey，脚本版的主页在 https://github.com/tiansh/yawf 那边。

**Comment by houwj** [comment]
扩展版，
点击缩略图后，“查看原图”链接不能对应所展示图片，
特别是多张GIF的(脚本版也有这个问题)，并且前后浏览后获取的URL还会错位，
几乎所有的多图都不正确，要么是undefined，要么是这条微博中的另一张图的链接(第一张总是第二张)，
而单图的，有些是undefined，
对缩略图右键后的“查看原图”是正确的链接，但有些GIF是空白页，

**Comment by tiansh** [comment]
我只能说我这正常，你还装了其他什么扩展/插件吗？（如果装了脚本版请先关掉脚本版，两个会冲突）

**Comment by houwj** [comment]
我知道有冲突。
禁用掉其他所有扩展，在虚拟机里新装的Firefox里，这两种情况下都会出现前面的情况。
脚本版的问题只是“多张gif时只能打开第一张”，这问题从微博用MP4代替gif之后就有了。
另外，脚本版和扩展版“查看原图”和“查看大图”两个链接的顺序是反的，不知道是不是故意的。

**Comment by tiansh** [comment]
给个链接？MP4代替GIF？所以脚本版也这样？

**Comment by houwj** [comment]
这里各种情况都能遇到 https://weibo.com/u/5955106173
只有“查看大图”时右上的“保存”按钮，才打开原gif图，其他看到的都是mp4。
WB_gif_box里的是gif，WB_gif_video_box里是对应的mp4。
脚本版目前就这个问题，扩展版的问题有点多。

**Comment by tiansh** [comment]
麻烦您详细说明一下：
1. 扩展相关功能的配置
2. 出问题的网址
3. 您是怎样操作的，每一步点了什么
4. 您看到的结果是什么样
5. 您希望的结果是什么样
谢谢

**Comment by tiansh** [comment]
修复了一个点动图会显示第一张图的问题，其他的问题我这无法复现，所以没有处理。
如果有遇到其他问题请按照上面说的清单说明一下问题的情况再随时打开这个问题。
