### ISSUE TITLE
恳请作者增加几个功能（内容基于脚本版）

### ISSUE THREAD

**Issue by cuoe** [tiansh/yaofang#10]
1、显示微博的实际发布时间（年/月/日/小时/分钟，如`2020-01-01 15:15`这样），而不是“X分钟前”（由于众所周知的原因，很多微博会被删除被屏蔽，急需及时保存留档）。就像安卓版客户端Share那样，某条微博在信息流里显示发布时间为“X分钟前”，点进该条微博则会显示实际发布时间，如下图。——我认为最好全部直接显示实际发布时间，否则在信息流/页面没有刷新时，即使过了很久也仍显示为X分钟前，毫无意义。

![1-1](https://user-images.githubusercontent.com/26758380/73119632-a17e9980-3f9f-11ea-9c9b-d65079fdf81d.jpg)

2、顶部导航栏自动隐藏功能，最好改为默认自动隐藏，而不是滑动页面时才会触发隐藏。毕竟大部分人日常基本用不到导航栏里的功能，既占用显示空间又影响截图或保存页面时的操作，需要时也只需鼠标移到顶部就会弹出，并不会带来不便。

3、浏览器原生播放器功能，最好能增加选择视频清晰度选项（或者默认最高清晰度，毕竟网页端一般没有流量忧虑），以及调整播放速度的选项，如0.5、1.5、2倍速三种即可（参照Share客户端）。

4、微博网页端仍有大量用户，药方这么好用的神器，用户量却并不算特别多，太不应该，我认为很大程度上在于设置过于复杂/繁琐。这个脚本我装了好几年却很少真正用上，每次打算设置时都因太复杂/繁琐而却步（我算是比较喜欢折腾的人），很多功能选项都要设置后刷新页面查看效果才能知道是否合适；同时也感觉还是差了些功能，但因为不想费工夫琢磨，也就没有把一些想法记录下来。最近仔细折腾了几天，效果还算清爽满意，花了很多小时。。。所以建议最好能有一个比较通用的默认配置模板，这样能让更多人拿来即用方便上手，或者在设置里增加一个选项/链接让大家能提交分享自己的配置。

还有些别的想法一时想不起来了，以后想起再来反馈。

感谢作者。祝您春节玉快，阖家欢落，幸福安康，万事如意。

**Comment by tiansh** [comment]
1. 时间这个可以搞，等我有空（如果有人要贡献代码，记得实现应该放在使用本地时区的功能里面）
2. 没太懂问题所在。现在是页面在最顶端的时候就显示，不在最顶端就不显示。所以不会造成占用显示空间的问题。毕竟截图的时候你可以稍微往下滑动一些。另外如果始终折叠的话，下面的位置都要网上挪，加上微博的主题（模板），顶部高度并不一样。导致移动的位置很难算。所以暂时不考虑这样改动。
3. 清晰度这个可以加个选项，不过还要再看一看。目前考虑是加一个清晰度的选项，选项为默认还是最好。
4. 感觉这些功能还是各取所需的，所以还没想改默认设置或者提供模板。至于分享平台我这也真的没法搞，毕竟我这根本没有服务器什么的。或许提示文字可以说的清楚一些，可是我也不知道该怎么弄。。。

**Comment by cuoe** [comment]
感谢回复。主要就是第一条比较需要。我真希望自己会写代码，有很多很多问题，搜不到解决办法，自己又无能为力，比如微博、豆瓣等一些网站的PWA版或移动版页面最近出现的一些非常操蛋的限制，这些服务为了把用户赶去APP客户端真是无所不用其极。

第二条说的就是页面在顶端时也默认自动隐藏。目前在截图或保存网页（保存为mhtml或PDF）时，稍微下滑一下就会划过头，需要下滑一下之后再拖住页面右边进度条才能准确定位，有时也会出现保存的内容再打开查看时，发现导航栏把下面的内容遮住了一两行的情况——这个问题在很多有顶部导航栏的网站上截图时都会遇到（使用浏览器截图扩展或截图软件都一样），我觉得这几年流行的这种导航栏比较反人类。这个功能不方便改动就算了，我操作麻烦一点而已。

视频我很少看，只是想着清晰度和播放速度选项是现在是视频播放的标配了，应该很多人需要吧。

谢谢。

**Comment by tiansh** [comment]
1, 3 已添加。
