### ISSUE TITLE
长微博无法自动展开

### ISSUE THREAD

**Issue by rockrong** [tiansh/yaofang#11]
在“微博展示”选项中选择了“自动展开超过xxx字符的微博”，但是选项并没有工作

**Comment by tiansh** [comment]
选项是怎么设置的，给个微博的例子，最好再给个截图，谢谢。

**Comment by rockrong** [comment]
设置如截图：https://imgur.com/X8q9B6n.png
微博显示的截图是这个样子的：https://imgur.com/fZ0M8G1.png

**Comment by tiansh** [comment]
你的设置里面填的是“自动展开不超过140字的微博，然后这条微博最后写着”展开全文（约480字）“。这可能就是原因了。

**Comment by rockrong** [comment]
但是这样不make sense啊~
应该怎么设置？选择更大的数值？用“眼不见心不烦”可以直接打开

**Comment by tiansh** [comment]
你把140改大了就大了啊？你是要问这个？

**Comment by rockrong** [comment]
我的问题是如何设置这个数值能让药方自动展开长微博

**Comment by tiansh** [comment]
你是说怎么改那个140的数字？那140是个输入框，你点一下，改最大就好了。

**Comment by rockrong** [comment]
谢谢~~这个逻辑上绕了一个小弯子~
