### ISSUE TITLE
[特性需求]希望增加一个快速拉黑的按钮

### ISSUE THREAD

**Issue by librix** [tiansh/yaofang#13]
因为不希望看到营销号，所以想把它们都拉黑。但是找到ID什么的，再点击等操作，拉黑的速度较慢。

因此希望在某条微博内，新增或改变一个按钮，点击后直接复制ID号，加入批量拉黑的后台进程中。

**Comment by tiansh** [comment]
脚本没有做任何针对关注列表的新增和移除等操作的计划。毕竟这种东西出问题会比较麻烦。

对于你说的情况，鼠标指向用户的时候，微博自带的有个弹框，显示用户详细信息，里面就有拉黑的按钮。是不是已经可以完成你要的功能了。不是的话，能不能具体描述一下你是想要什么样的效果？

**Comment by librix** [comment]
哦哦，确实是这样，因为是异步加载，【鼠标指向用户的时候，微博自带的有个弹框】的显示时间太长。我希望能后台完成这个过程。

假如可能的话，我想能不能加一个如图所示的功能？
![image](https://user-images.githubusercontent.com/10742127/75686262-e9978700-5cd6-11ea-9670-2799b337970e.png)

或者这样：
![image](https://user-images.githubusercontent.com/10742127/75686835-d6d18200-5cd7-11ea-9daf-0e98b2fc7866.png)

假如不困难的话。

结果是点击之后，这条微博以及微博**作者**所发的所有微博都会隐藏。换句话说，就是按账号屏蔽。

**Comment by librix** [comment]
另外我目前在用脚本的这个功能，希望增加如下两个选择项：

- [ ] 加入黑名单。
- [ ] 加入黑名单时，隐藏该微博账户的所有博文【发现页面】【个人首页】。
