### ISSUE TITLE
内容过滤与作者过滤

### ISSUE THREAD

**Issue by davidfromtheeast** [tiansh/yaofang#14]
现在分别有内容过滤和作者过滤，但还是有一些不方便，不知是否可以把两者结合起来，制作一个新的基于作者加内容的过滤，比如内容过滤“美食”，现在过滤所有包含“美食”的微博，如果能限制到只过滤某个作者下面的包含“美食”的微博就更完美了。

**Comment by tiansh** [comment]
目前按照关键词匹配是不包括作者信息的。但是按照正则式匹配是包括作者信息的。你可以在设置里面启用调试，将按正则式过滤的文本打印到控制台。然后参考生成的文本来书写一下规则。就可以将某人发布的，包含特定关键词的微博过滤掉了。

如果你觉得这个功能可以的话，后续我们可以考虑在识别作者的时候附带一个作者 id。

**Comment by davidfromtheeast** [comment]
> 目前按照关键词匹配是不包括作者信息的。但是按照正则式匹配是包括作者信息的。你可以在设置里面启用调试，将按正则式过滤的文本打印到控制台。然后参考生成的文本来书写一下规则。就可以将某人发布的，包含特定关键词的微博过滤掉了。
> 
> 如果你觉得这个功能可以的话，后续我们可以考虑在识别作者的时候附带一个作者 id。

正则下我单独作者和单独内容都可以做到过滤，但是连起来却不知道怎么做。

**Comment by tiansh** [comment]
## 同时满足若干个规则

举例：/^(?=[\s\S]*抽)(?=[\s\S]*送)/

说明：使用 /^(?=[\s\S]*XXX)(?=[\s\S]*YYY)(?=[\s\S]*ZZZ)/ 的格式可以匹配同时满足XXX、YYY和ZZZ等三条规则的字符串。比如上面举例的这条规则可以匹配同时带有“抽”和“送”两个字的微博。如果你好奇这是怎么工作的，这里有具体地说明（当然，看不懂不会影响你用这个强大的过滤规则）： ^ 表示从字符串开始的位置匹配； (?=xxx) 表示匹配规则xxx，但是不捕获（大概可以理解为检查后面是不是匹配特定规则，但是检查之后光标不往后移动）； [\s\S]* 表示从开头到要匹配的规则之间可以有任意的内容。



举例：/^(?=[\s\S]*转发)(?=[\s\S]*(好事|好运|中奖|运气|锦鲤|许愿|愿望|实现))/

说明：这条规则可以匹配出现“转发”一词的同时，出现后面这些词中的任意一个的微博。

**Comment by davidfromtheeast** [comment]
> ## 同时满足若干个规则
> 举例：`/^(?=[\s\S]*抽)(?=[\s\S]*送)/`
> 
> 说明：使用 `/^(?=[\s\S]*XXX)(?=[\s\S]*YYY)(?=[\s\S]*ZZZ)/` 的格式可以匹配同时满足XXX、YYY和ZZZ等三条规则的字符串。比如上面举例的这条规则可以匹配同时带有“抽”和“送”两个字的微博。如果你好奇这是怎么工作的，这里有具体地说明（当然，看不懂不会影响你用这个强大的过滤规则）： ^ 表示从字符串开始的位置匹配； `(?=xxx)` 表示向前匹配规则xxx（大概可以理解为检查后面是不是匹配特定规则，但是检查之后光标不往后移动）； `[\s\S]*` 表示从开头到要匹配的规则之间可以有任意的内容。
> 
> 举例：`/^(?=[\s\S]*转发)(?=[\s\S]*(好事|好运|中奖|运气|锦鲤|许愿|愿望|实现))/`
> 
> 说明：这条规则可以匹配出现“转发”一词的同时，出现后面这些词中的任意一个的微博。

懂了，已搞定。
其实还是我正则知识不够，谢谢指导。
