### ISSUE TITLE
与uBlock Origin冲突

### ISSUE THREAD

**Issue by itheabyss** [tiansh/yaofang#16]
微博展示--图片与视频--查看图片添加原图链接--【包含原图的网页】，每次点击图片新打开的页面会被uBlock Origin拦截并且直接关闭，也就是说根本打不开。

选择【原图】，没有问题。

**Comment by tiansh** [comment]
我这没有这个问题。

你用的是脚本版吗。如果是脚本版请参考下这个：https://github.com/tiansh/yawf/issues/139#issuecomment-529358542
