### ISSUE TITLE
添加导入关注列表功能，一键添加关注

### ISSUE THREAD

**Issue by bingo8670** [tiansh/yaofang#17]
因为最近被炸号了，换了新号后，一个个添加关注比较麻烦，希望能开发一个“导入关注列表，一键添加关注”的功能；
有这个功能以后，也可以分享给朋友自己的关注列表，然后关注，比较高效，谢谢。

**Comment by tiansh** [comment]
做不到。关注几个就开始要验证码了。所以没办法做导入。
