### ISSUE TITLE
请增加适配https://m.weibo.cn的功能

### ISSUE THREAD

**Issue by alextooter** [tiansh/yaofang#18]
用pc浏览m.weibo.cn的页面非常清爽，

如果能支持这个域名的页面就好了，只支持“根据关键字、作者、来源等隐藏、折叠或高亮微博；使用拖拽轻松定义过滤规则；”功能就很完美了。

谢谢

**Comment by tiansh** [comment]
没打算做。

**Comment by tiansh** [comment]
可以看看谁有兴趣做一个。我这应该没空做这个。
