### ISSUE TITLE
希望增加“过滤个人主页赞过的微博”

### ISSUE THREAD

**Issue by Alphabet1226** [tiansh/yaofang#19]
希望可以增加支持打开某个账号的个人主页后，只显示他自己的微博，不显示他赞过的微博。

**Comment by tiansh** [comment]
你打开了

隐藏以下微博 - 广告/商品/推荐 - 混入个人主页的赞过的微博

这个功能吗？这个功能故障了？

**Comment by Alphabet1226** [comment]
> 你打开了
> 
> 隐藏以下微博 - 广告/商品/推荐 - 混入个人主页的赞过的微博
> 
> 这个功能吗？这个功能故障了？

刚去看了眼确实是打开的，但个人主页还是会混入赞过的微博，应该是故障了。

**Comment by tiansh** [comment]
给个截图和链接？我去看看

**Comment by Alphabet1226** [comment]
> 给个截图和链接？我去看看
https://weibo.com/lyfba?topnav=1&wvr=6&topsug=1&is_all=1
![截图_2020041817363736SS.png](https://i.loli.net/2020/04/18/SB9X5LyazPTmvnl.png)
![截图_2020041817283628SS.png](https://i.loli.net/2020/04/18/RhltskMiZK8b5OD.png)

**Comment by tiansh** [comment]
确认了一下，这个功能目前企业认证用户的个人主页上工作不正常。下个版本处理。

目前你还可以勾选“推广微博/粉丝通微博/品牌速递/好友赞过的微博”，也会把这条给隐藏掉。

**Comment by Alphabet1226** [comment]
好的，感谢作者。
