### ISSUE TITLE
微博宽度加宽后时间轴错位

### ISSUE THREAD

**Issue by Anaraky** [tiansh/yaofang#2]
Firefox  Version `66.0.4`
yaofang Version `0.0.16`

药方设置微博宽度为 1010 后，个人主页中的时间轴出现错位的情况
![yaofang](https://user-images.githubusercontent.com/5061703/57432376-461d4780-7268-11e9-8f70-18d9602a6b3a.jpg)

脚本版 YAWF 同样的宽度就没有问题
![YAWF](https://user-images.githubusercontent.com/5061703/57432095-73b5c100-7267-11e9-823e-72b8c6062133.jpg)

**Comment by tiansh** [comment]
两个有一些功能是单独做的，所以有这种情况也正常。更新一下，应该解决了。
