### ISSUE TITLE
希望有一个一键取消赞并拉黑的功能

### ISSUE THREAD

**Issue by JolyonJostar** [tiansh/yaofang#20]
微博会给莫名其妙的微博点赞，时间一久就攒了很多，手动取消拉黑有点麻烦，如果技术允许的话希望能在“我的赞”页面，能够对单条微博取消赞并拉黑

**Comment by tiansh** [comment]
脚本/扩展无意做任何操作关注列表的功能，以避免任何可能的误关注/误取消关注赖在我们头上。
