### ISSUE TITLE
希望大佬可以添加个批量导出导入黑名单列表的功能

### ISSUE THREAD

**Issue by dongduoduo2011** [tiansh/yaofang#23]
qwq方便炸号之后回血

另外就是希望能让关注列表也有类似功能，之前只能导出列表而不能批量关注，感觉可以参考一下https://github.com/nondanee/weiboBatchFollow 然后整合进来（

**Comment by tiansh** [comment]
这脚本没打算做任何操作关注列表的功能，也不打算做批量相关的功能。如果你想贡献代码可以看一下 https://github.com/tiansh/wbg ，不然应该短期内没人管这个。
