### ISSUE TITLE
“按原作者过滤”功能无法显示也无法生效

### ISSUE THREAD

**Issue by RichardCassell** [tiansh/yaofang#26]
YAWF版本4.0.58，时间是2020年5月15日，使用平台Chrome浏览器，版本81.0.4044.138，问题表现为，屏蔽用户数量较多时，脚本”按原作者过滤“页面无法查看，在网页浏览中也无法生效。界面截图和使用的脚本配置在附件中。
![issue](https://user-images.githubusercontent.com/49812158/82045128-245b6980-96e1-11ea-8943-ef757279fcd8.png)

[心疲力竭XJS-药方设置-20200515.zip](https://github.com/tiansh/yaofang/files/4634017/XJS-.-20200515.zip)

**Comment by RichardCassell** [comment]
补充，使用的是Tampermonkey，版本4.10。

**Comment by tiansh** [comment]
我这看到的情况是你的配置文件里面 877 行，2021 行有两个 null。不知道这两条数据是怎么加进去的，不过应该是这两条数据导致的问题。

临时的解决办法是把这两个 null （连同上一行的逗号）删掉，之后再导入回来。

**Comment by tiansh** [comment]
你能否回忆一下出问题之前最后添加的那一个是怎么添加的。应该是那个时候添加的有问题导致的。
目前的解决办法应该是把错误数据清理掉……

**Comment by RichardCassell** [comment]
删掉877行和2021行的null以后恢复正常了，非常感谢。
我不确定是哪次添加导致的结果，但是后来尝试复现问题的时候发现，如果在微博首页，将鼠标指针放在博主id上，通过拖动“弹出画面中博主头像”方式进行屏蔽操作，如果博主信息加载不完全，就会导致出现Null的结果。不知道这个信息是否有帮助。
“弹出画面”的样式如附图所示。
再次感谢您对脚本的开发和维护！=V=
![image](https://user-images.githubusercontent.com/49812158/82118756-deb7a300-97ab-11ea-80a9-b429413b0c4e.png)

**Comment by tiansh** [comment]
总之新版处理了一下这个情况，会自动把 null 删掉。我也不知道怎么加进去的就是了。
