### ISSUE TITLE
“头条文章不关注作者直接显示全文”失效？

### ISSUE THREAD

**Issue by Adiwon** [tiansh/yaofang#3]
Cent browser 4.0.9.112  (Chromium 74.0.3729.169)
Tampermonkey 8.41
药方4.0.35

随便找了篇文章，比如这个 https://weibo.com/ttarticle/p/show?id=2309404399209255141472
设置里勾选了“头条文章不关注作者直接显示全文”，但还是要求关注可见

**Comment by tiansh** [comment]
感谢反馈，下个版本处理

**Comment by tiansh** [comment]
应该好了。
