### ISSUE TITLE
任意微博详情页，拖拽评论里的任意用户到“创建过滤规则”，都会提示null

### ISSUE THREAD

**Issue by Alphabet1226** [tiansh/yaofang#32]
![image.png](https://i.loli.net/2020/06/25/tDXhSyl596em4Ii.png)

**Comment by tiansh** [comment]
应该已经解决了，更新试试。

**Comment by Alphabet1226** [comment]
> 应该已经解决了，更新试试。

已更新，完美解决。感谢
