### ISSUE TITLE
同框架内页面切换时 onconfigchange 未被触发

### ISSUE THREAD

**Issue by Konano** [tiansh/yaofang#34]
我觉得不能用 CONFIG 了，直接爬网页元素

**Comment by tiansh** [comment]
框架？你说 <frame>？

**Comment by Konano** [comment]
简单来说就是从个人主页切换到首页的时候，页面内 CONFIG 并没有更新……

**Comment by tiansh** [comment]
我这试了试都是更新了的？没更新是怎么回事？

**Comment by Konano** [comment]
我把插件卸载后，微博原网页也没有更新啊……（用的是油管猴的插件）

**Comment by tiansh** [comment]
我这只要切换到个人主页，就会刷新页面，这些也都会重置掉。。。没办法复现。尤其你说不开插件也有问题，就完全不知道了

**Comment by Konano** [comment]
唔，那能留个通讯方式吗？我邮箱是 nanoapezlk@gmail.com 直接发到我邮箱就行，因为觉得通过 GitHub Issues 交流效率太低了……
我这边大概会把我遇到的情况跟您详细复现一次。

**Comment by tiansh** [comment]
你可以直接微博私信 @YAWF脚本 ……
