### ISSUE TITLE
希望增加过滤“仅@”的评论

### ISSUE THREAD

**Issue by Alphabet1226** [tiansh/yaofang#35]
一来很多人喜欢@印象笔记保存微博，二来很多人误把@当分享，喜欢在微博评论区@自己好友。希望可以增加个选项屏蔽掉这些。

**Comment by tiansh** [comment]
评论过滤里面现有的“隐藏没有内容的评论（只有表情、提到等）”能满足你的需求吗？

**Comment by Alphabet1226** [comment]
> 评论过滤里面现有的“隐藏没有内容的评论（只有表情、提到等）”能满足你的需求吗？

wow感谢！正是我的需求，之前一直没有发现这里。
