### ISSUE TITLE
更新后不能保存设置时什么情况

### ISSUE THREAD

**Issue by sy1412** [tiansh/yaofang#37]
就最近更新才发现 不能保存任何设置 一刷新就还原 
因为总提示那个更新后有哪些内容的消息框 每次刷新就弹出 点掉不更新提示也照常
才发现不对劲 我重置/重装了也不好使 求助

**Comment by sy1412** [comment]
我是安装的FIREFOX的扩展

**Comment by sy1412** [comment]
Yaofang | Error while handling storage:  Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.
看控制台好像是这个原因？

**Comment by tiansh** [comment]
试试临时的解决方法：
在设置里面试着重置手动隐藏微博的列表，关掉自动检查关注列表，并清空现有的关注列表。

**Comment by sy1412** [comment]
现在正常了 。。。

**Comment by tiansh** [comment]
啊，之前更新完了忘记在这里说了……
