### ISSUE TITLE
t.cn短网址对于部分网站不提供自动跳转了

### ISSUE THREAD

**Issue by Franinc** [tiansh/yaofang#41]
如题，比如这个：https://t.cn/A6USGUwR 
点开后只会提示“如需浏览，请长按网址复制后使用浏览器访问 https://www.pixiv.net/artworks/83549605”
不知道大佬是否有兴趣加个自动跳转功能

**Comment by tiansh** [comment]
更新了一个自动跳转的功能，不确定能用多久，看情况再处理。

**Comment by Franinc** [comment]
感谢大佬！

**Comment by pixiandouban** [comment]
Tampermonkey 脚本版的 药方可以跳转；
Firefox 插件版的不能跳转，不记得什么时候开始的。

**Comment by Geeyun-JY3** [comment]
被警告 `访问的网址可能存在风险` 的短链接好像可能会闪几次才跳转，如：http://t.cn/RPZXeNY
