### ISSUE TITLE
允许首页右边栏随页面滚动始终显示无效？

### ISSUE THREAD

**Issue by WaylanPunch** [tiansh/yaofang#43]
设置->版面展示->边栏->**合并左右边栏到右侧** and **统一各类页面侧栏到右侧**。
此时选中**随页面滚动元素**->**允许首页左边栏随页面滚动始终显示**才能控制右边栏，
按理说是不是应该选中**允许首页右边栏随页面滚动始终显示** ？

- 浏览器：Edge
- 浏览器版本：85

**Comment by tiansh** [comment]
合并归合并，那个还是叫左边栏。

然后如果你把左边栏的滚动关掉，同时打开右边栏的滚动，那么右边栏默认跟随滚动的元素会跟随。

如果你打开了左边栏的跟随滚动，那么右边栏会强制为不跟随（不然两个都跟着就乱了）。

如果两边的都没开，就不会跟着跑。

这个行为是设计成这样的。虽然可能有些迷惑，不过也没有更好的方式来处理。不然用起来会更迷惑。
