### ISSUE TITLE
希望能隐藏微博自带的生日提醒

### ISSUE THREAD

**Issue by Alphabet1226** [tiansh/yaofang#45]
如图
![image](https://user-images.githubusercontent.com/51783873/96000322-57a94c80-0e69-11eb-97ed-610a56574767.png)

**Comment by tiansh** [comment]
按来源过滤自己添加规则就行。不过这个只是隐藏，不会阻止它发出来。

**Comment by Alphabet1226** [comment]
> 按来源过滤自己添加规则就行。不过这个只是隐藏，不会阻止它发出来。

感谢，已解决！因为我一直开着隐藏微博来源，没意识到可以通过这种方法来隐藏。
