### ISSUE TITLE
有关开启插件的“阅读视图”，页面一些排版问题的反馈

### ISSUE THREAD

**Issue by MI55-845** [tiansh/yaofang#5]
###  脚本版本：

4.0.47版

### 问题描述：

**未开启“阅读视图”，页面正常。
开启“阅读视图”，在“我的首页”页面出现页面排版问题，附上截图**

![1](https://user-images.githubusercontent.com/44739100/66020709-95fff200-e51a-11e9-9b93-8d158344a0bf.png)

**在下拉过程中，左栏会一起动，当然我翻了翻插件，发现把“允许首页左边栏随页面滚动始终显示”功能关闭，左边栏就不会动了**

![2](https://user-images.githubusercontent.com/44739100/66020716-9dbf9680-e51a-11e9-86a0-3946b8849c82.png)

**以前开启“阅读视图”是没有头部部分（红色框内的部分）和左栏的，如图**

![3](https://user-images.githubusercontent.com/44739100/66021101-0e1ae780-e51c-11e9-9d09-013f64801a03.png)

**“允许首页左边栏随页面滚动始终显示”这个功能，我不知道你是什么时候添加的，我没有使用过这个功能，以前开启“阅读视图”也是没有左栏出现的。**

### 期望的修改效果：

希望可以恢复到以前的样子，当然只是看着不是很舒服，不影响其他功能。

麻烦作者了，感谢。

**Comment by tiansh** [comment]
感谢反馈，之前更新弄出来的一个问题。下次修……

**Comment by tiansh** [comment]
应该好了
