### ISSUE TITLE
过滤特定关注用户包含关键字微博的功能

### ISSUE THREAD

**Issue by idjun01** [tiansh/yaofang#50]
是否考虑添加过滤特定关注用户包含关键字微博的功能？比如我想屏蔽用户A包含「aaa」内容的微博，但其他人发「aaa」可以不过滤的那种？

**Comment by tiansh** [comment]
正则里面写 /^(?=.*^@A)(?=.*aaa)/试试吧。。。

**Comment by idjun01** [comment]
后者可以，谢谢啦！
