### ISSUE TITLE
请问如何屏蔽“Complete Profile"和"Friend Recommendation"?

### ISSUE THREAD

**Issue by refo2613** [tiansh/yaofang#56]
请问如何屏蔽“Complete Profile"和"Friend Recommendation"?

常常会显示在中间（我关注的播客发言）的上方。

谢谢。

**Comment by tiansh** [comment]
你说的这两个东西有中文吗，在哪个页面上？
我有点不知道你说的是什么……

或者你配个截图？

**Comment by tiansh** [comment]
新版微博 V7 界面还是旧版微博 V6 界面？

**Comment by refo2613** [comment]
http://wx1.sinaimg.cn/mw690/008hs6C6gy1gpqhjbsngvj30wu0pkwkm.jpg

我上传了 一个截图，麻烦你看一下。
英文是因为我的浏览器，为了办公方便，默认是英文的。

**Comment by refo2613** [comment]
应该是老款的界面，因为我觉得新款不好看，不想升级。

**Comment by tiansh** [comment]
试试 隐藏模块 - 中栏 - 微博兴趣推荐（顶部）

**Comment by refo2613** [comment]
Feed Recommendation, top
我已经勾上了。

**Comment by refo2613** [comment]
不幸的是，依然有推荐。

http://wx1.sinaimg.cn/mw690/008hs6C6gy1gpr70k2nkuj314r0mnaex.jpg

**Comment by refo2613** [comment]
我自己找到关闭推荐的方式了。在WEIBO自身的隐私设置里。

**Comment by refo2613** [comment]
发现WEIBO自己的隐私设置无效，或者说不是这个。哎。。。
