### ISSUE TITLE
过滤热搜榜单中推荐话题

### ISSUE THREAD

**Issue by watashihame** [tiansh/yaofang#57]
在微博V7界面中，热搜榜单会出现推荐话题，能否添加热搜榜单内的过滤选项？
![image](https://user-images.githubusercontent.com/15100339/118351956-5ec84280-b591-11eb-9997-e56177242f79.png)

**Comment by tiansh** [comment]
这个直接归类到“界面清理 - 隐藏模块 - 杂项 - 广告”里面了。打开那个之后你看看还在吗

**Comment by watashihame** [comment]
> 这个直接归类到“界面清理 - 隐藏模块 - 杂项 - 广告”里面了。打开那个之后你看看还在吗

感谢，已经解决了。
