### ISSUE TITLE
没有Google Chrome版的yaofang吗？

### ISSUE THREAD

**Issue by Vstory** [tiansh/yaofang#6]
Chrome网上应用商店，好像没有该扩展。不上架Chrome网上应用商店吗？

**Comment by tiansh** [comment]
没有，脚本版 https://github.com/tiansh/yawf 可以支持包括 Google Chrome 在内的大部分浏览器。

**Comment by tiansh** [comment]
目前已知的几个不兼容 Chrome 的部分包括：
0. manifest.json 需要提供单独的版本，图标需要提供单独的版本（Chrome 对 svg 图标支持不好）
1. Chrome 73+ 不允许从 content script 发跨源请求；但是因为 Firefox 的 background script 目前没有合适的方式处理容器，所以目前的请求都是从 content script 发送的；好在 Chrome 不支持容器，所以如果需要移植，这里要改成后台发送请求。
2. 聊天框使用一个特殊的域名做了一层跳转来屏蔽扩展的域名，Chrome 不支持这种写法（.invalid 域名会在发送请求之前直接因为 URL 非法被阻止），而且也不需要这层额外的跳转。所以如果移植，要把这段给去掉。
3. Chrome 对 storage 的尺寸和读写频率的限制更多一些，所以如果需要移植，这里也需要再包一层；

我这目前没有相关移植的打算。

**Comment by Vstory** [comment]
好的，感谢您的回复。
