### ISSUE TITLE
导航栏清理问题

### ISSUE THREAD

**Issue by DCxDESIGN** [tiansh/yaofang#67]
> 微博前段时间更新了导航栏，新增了下图中的两个按钮
> 
> ![image](https://user-images.githubusercontent.com/48208459/157197298-48db710b-7970-49fa-8d9e-9db65877b179.png)
> 
> 而如果选中了清理界面中的“游戏”，现在会隐藏个人主页的入口，取消勾选后会恢复正常：
> 
> ![image](https://user-images.githubusercontent.com/48208459/157197541-2d0e1b31-275d-4d8d-baca-9c553d6cda03.png)
> 
> 还请更新脚本以跟进此次变动，非常感谢

以上内容已修复，非常感谢，新反馈另发一条

**Comment by DCxDESIGN** [comment]
上面的问题已经修正了，非常感谢，另外新发现了一个问题，微博详情/个人主页 等 非首页 的页面，导航栏的“游戏”依然会显示

![image](https://user-images.githubusercontent.com/48208459/157308376-e9497e87-6cf5-4c80-88ff-8c196a297459.png)

还请核实并跟进，谢谢

**Comment by tiansh** [comment]
感谢反馈……orz

**Comment by DCxDESIGN** [comment]
已经修复了，非常感谢
