### ISSUE TITLE
浏览器在175%缩放下 导航栏左上角微博字样显示异常

### ISSUE THREAD

**Issue by tdzdzn** [tiansh/yaofang#68]
https://sm.ms/image/7ZrTAB8SfzQeKgM
https://sm.ms/image/LE4vVcjaUutT5lk

如图所示，150%缩放下不会显示微博字样，175%缩放下会显示微博字样，且和右边的按钮位置冲突

**Comment by tiansh** [comment]
图标应该在右侧啊，你这是屏幕宽度很窄吗？

**Comment by tdzdzn** [comment]
想起来我装了Weibo_v6的样式，应该和皮肤有关系，那没事了
