### ISSUE TITLE
有关图片无法显示的问题

### ISSUE THREAD

**Issue by MI55-845** [tiansh/yaofang#7]
**脚本版本：**

4.0.52版

**问题描述：**

今天（10/30）突然发现有些微博图片无法显示

经过观察应该是微博有**超过9张**的图片在开启了 

“支持超过9张配图的微博”的功能 后图片无法显示了，附图：

当然  “查看图片添加“查看原图”链接” 和 “查看图片添加“批量下载”链接” 功能 我也是开启着的

![1](https://user-images.githubusercontent.com/44739100/67841475-1e31e100-fb33-11e9-855c-1d03b705118d.jpg)

当关闭“支持超过9张配图的微博”的功能后图片正常显示，附图：

![2](https://user-images.githubusercontent.com/44739100/67841492-2be76680-fb33-11e9-89cd-1682918257ca.jpg)

我也不知道这是不是我个人出现的情况。我尝试了 “支持超过9张配图的微博”的功能 中的所有选项都不能正常显示超过9张的图片，就来反馈一下。

**Comment by tiansh** [comment]
更新一下，应该好了。
