### ISSUE TITLE
功能申请：视频下载按钮

### ISSUE THREAD

**Issue by YingfenYi** [tiansh/yaofang#73]
感谢作者提供的插件，批量打包下载图片的功能很好用，想问下能不能给视频也添加个下载按钮/选项？目前好像没看到相关的设置
谢谢！

**Comment by tiansh** [comment]
打开使用原生播放器，然后右键下载？

**Comment by YingfenYi** [comment]
> 打开使用原生播放器，然后右键下载？

谢谢！以前都没用过这个原生播放器的功能，确实可以下载
