### ISSUE TITLE
是否支持新版微博？

### ISSUE THREAD

**Issue by Jefffish09** [tiansh/yaofang#79]
一直在用旧版微博，今天打开就自动变成新版，发现找不到药方设置入口。

手动换回旧版，提示说近期会下线旧版，所以想问问脚本支持新版微博吗？

![image](https://user-images.githubusercontent.com/44800122/201243673-e3d50877-963e-4a88-8391-a14d42dcf4bb.png)

**Comment by wuzh07** [comment]
新版微博页面右上角齿轮里可以看到药方设置入口，不过只支持新版微博的部分功能

**Comment by Jefffish09** [comment]
> 似乎右上角齿轮里面也没有（已刷新过）
![image](https://user-images.githubusercontent.com/44800122/201308059-9b7c2d43-f932-439c-85fb-7b835ed4ce18.png)

**Comment by wuzh07** [comment]
多刷新几次呢（我也不清楚，玄学😂
![image](https://user-images.githubusercontent.com/15119543/201308932-e09a0dbe-c2f8-468c-ba8c-8f3bdbf5449c.png)

**Comment by Jefffish09** [comment]
> 多刷新几次呢，我在用得版本是4.0.103（我也不清楚，玄学😂 ![image](https://user-images.githubusercontent.com/15119543/201308932-e09a0dbe-c2f8-468c-ba8c-8f3bdbf5449c.png)

同样版本，使劲刷新了，还是没出现，换回旧版就能看到设置入口。
![image](https://user-images.githubusercontent.com/44800122/201316077-4b0d9b1a-d9a9-4a17-8b21-9a4091d2a182.png)

![image](https://user-images.githubusercontent.com/44800122/201316212-02609d94-336b-4802-b611-b4fbc25d61ee.png)

**Comment by Jefffish09** [comment]
似乎发现解决方案了。

在旧版时，关掉这个
![image](https://user-images.githubusercontent.com/44800122/201503467-c292fa7e-57fe-4a5c-bda3-bff7a5beef61.png)

然后切换到新版就能正常出现药方的设置入口了
![image](https://user-images.githubusercontent.com/44800122/201503490-df6d1a62-ad78-4ddb-b09b-a5323e70cc77.png)

**Comment by tiansh** [comment]
那个设置应该不是太影响，我更新了一版，不知道有没有好一些。

**Comment by Jefffish09** [comment]
> 那个设置应该不是太影响，我更新了一版，不知道有没有好一些。

更新，试了，还是同样问题。
