### ISSUE TITLE
极少部分微博的尾巴显示为HTML代码

### ISSUE THREAD

**Issue by Jefffish09** [tiansh/yaofang#82]
今天发现极少部分微博的尾巴变成HTML代码，反复刷新还是异常，目前没发现规律。脚本版本Yet Another Weibo Filter (药方) 5.0.108，关掉脚本就能恢复正常。

![image](https://github.com/tiansh/yaofang/assets/44800122/cae96394-1a29-4d7b-b914-2ac9b95fe534)

**Comment by millionart** [comment]
修改微博显示逻辑以允许相关改造功能 关掉就好了
