### ISSUE TITLE
时间线正文区域评论配图无法直接查看原图

### ISSUE THREAD

**Issue by microka** [tiansh/yaofang#9]
Google Chrome：79.0.3945.117 (正式版本) （64 位）
操作系统：Windows 10 OS Version 1909 (Build 18363.592)
药方：v4.0.57

药方设置如下：
![微信截图_20200115210110](https://user-images.githubusercontent.com/490351/72436449-64661a80-37db-11ea-97b7-10d7eef0a63d.png)

在微博首页时间线，某条微博正文区域出现的［评论配图］，点开后点击下一层页面的［查看原图］，此时打开的是一个内嵌了 bmiddle 规格图片的页面，展示的图片链接为 https://wx2.sinaimg.cn/bmiddle/******.jpg

图例：
![2020-01-15_210620](https://user-images.githubusercontent.com/490351/72436697-04bc3f00-37dc-11ea-9f0c-91aa4c5ebf1f.png)

![2020-01-15_210501](https://user-images.githubusercontent.com/490351/72436703-08e85c80-37dc-11ea-9d80-94cd420329b0.png)

![2020-01-15_210824](https://user-images.githubusercontent.com/490351/72436709-0d147a00-37dc-11ea-9a60-581d4fbe351a.png)

不知能否针对该场景下增加一键查看原图的功能？

**Comment by tiansh** [comment]
目前如果你勾选那个点击缩略图时直接查看原图就会直接在新页面打开图片了。

**Comment by tiansh** [comment]
更新的 58，你现在也可以右键新标签页打开查看原图，或者按住 Ctrl 查看原图了。
